name: CI-Train

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: MLProject/conda.yaml
          activate-environment: house_price_env

      - name: Run MLflow Project
        run: |
          cd MLProject
          mlflow run .
